version: '3.9'

services:
  mariadb:
    image: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    image: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      WORDPRESS_DB_NAME: ${DB_NAME}
      WP_USER: user
      WP_PASS: pass
      WP_TITLE: fvoicu
      WP_HOST: fvoicu.42.fr
      WP_ADMIN_USER: big_user
      WP_ADMIN_PASS: big_pass
      WP_ADMIN_MAIL: big_user@example.com
      WP_MAIL: random_user@example.com
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/wordpress
    env_file:
      - .env

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/wordpress
    restart: always

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/fvoicu/data/mariadb
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/fvoicu/data/wordpress

networks:
  inception:
    driver: bridge
